CREATE TABLE weather
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    station_code VARCHAR(3) NOT NULL,
    collected_at TIMESTAMP  NOT NULL,
    received_at  TIMESTAMP  NOT NULL,
    temperature  DOUBLE PRECISION,
    humidity     DOUBLE PRECISION,
    wind_speed   DOUBLE PRECISION,
    CONSTRAINT chk_weather_timestamps CHECK (collected_at <= received_at)
);

CREATE INDEX idx_weather_station_received_at
    ON weather (station_code, received_at);
